
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    environment: "dev",

    env_demo_key: "env_demo_key_default",
    env_demo_name: "env_demo_name_value",
    env_demo_url: "https://env_demo_url.com"
  };
